/**
 * FAQ content, grouped by topic.
 *
 * Shared between the compact accordion on the marketing pages and the full FAQ
 * on the landing page, so an answer is only ever written once.
 *
 * The boundaries of the service are stated here deliberately and repeatedly:
 * we do not award scholarships, we do not decide admissions, and we do not
 * write essays for students. Students should not be able to miss it.
 *
 * An `answer` is either a string or an array of strings, one per paragraph.
 */

export const FAQ_GROUPS = [
  {
    id: "application",
    title: "Applications",
    blurb: "How applying works, and what we do and do not do.",
    faqs: [
      {
        question: "Do you award scholarships or make admission decisions?",
        answer:
          "No. myScholy is not a scholarship provider or a university. We collect and verify scholarship opportunities from universities, governments, and organizations, but every application is reviewed and decided by the institution offering the opportunity.",
      },
      {
        question: "Can you guarantee I will receive a scholarship?",
        answer:
          "No. No one can honestly guarantee a scholarship or admission. Final decisions are made by the scholarship provider. Our goal is to help you submit the strongest application possible by improving the quality of your materials and making sure nothing important is missed.",
      },
      {
        question: "How do I find scholarships that match me?",
        answer:
          "Use the filters on the Scholarships page to search by country, degree level, and application status. Every listing links directly to the official scholarship page for complete details.",
      },
      {
        question: "Can I apply for more than one scholarship?",
        answer:
          "Yes. Many students apply for several scholarships at the same time. Just make sure every application is tailored to the specific scholarship instead of submitting the same materials everywhere.",
      },
      {
        question: "What documents are usually required?",
        answer:
          "Requirements vary, but most scholarships ask for academic transcripts, a personal statement, recommendation letters, proof of identity, and sometimes proof of language ability or financial need. Always check the official scholarship page for the exact requirements.",
      },
      {
        question: "What services will myScholy Consulting provide?",
        answer:
          "Our consulting service is designed to support students throughout the application process. Services will include eligibility reviews, application planning, essay editing, CV or résumé reviews, interview preparation, and final application checks before submission.",
      },
      {
        question: "Is consulting available now?",
        answer: "Not yet. We are currently working to launch it soon.",
      },
    ],
  },
  {
    id: "essays",
    title: "Essays & Documents",
    blurb: "Our specialty - and the line we do not cross.",
    faqs: [
      {
        question: "Will you write my scholarship essay for me?",
        answer:
          "No. Every essay must be written by the student. We do not write personal statements, scholarship essays, or application responses on behalf of applicants.",
      },
      {
        question: "Can I use AI to write or edit my essay?",
        answer: [
          "No. Your essay must be your own work. We do not accept essays that have been written or substantially generated by AI.",
          "Before we begin editing, we review every draft for 100% authenticity or originality. If we believe an essay relies heavily on AI-generated content or does not reflect the applicant's own writing, we will not proceed with editing. Our role is to improve essays that students have written themselves, not to rewrite or generate them. This policy helps protect your application and ensures your submission reflects your own experiences, ideas, and voice.",
        ],
      },
      {
        question: "What kind of essay support do you provide?",
        answer:
          "We review and improve essays that you have already written. Our feedback focuses on structure, clarity, grammar, flow, and whether your essay answers the prompt effectively while keeping your voice and ideas intact.",
      },
      {
        question: "What if I haven't written anything yet?",
        answer:
          "That's completely fine. We can help you organize your ideas, identify your strongest experiences, and suggest a structure to follow. Once you've written a draft, we'll help you improve it.",
      },
      {
        question: "Do you also review CVs and résumés?",
        answer:
          "Yes. We review CVs and résumés for formatting, clarity, organization, grammar, and presentation so they better reflect your achievements and experience.",
      },
    ],
  },
  {
    id: "fees",
    title: "Fees & Payments",
    blurb: "What costs money, what never will, and how to spot a scam.",
    faqs: [
      {
        question: "Is myScholy free?",
        answer:
          "Yes. Browsing, searching, and applying through the myScholy scholarship board is completely free. Our consulting services are optional and offered separately. You are free to use the platform to find and apply for scholarships on your own without paying anything.",
      },
      {
        question: "How much will consulting cost?",
        answer:
          "Our consulting prices will be published when the service officially launches. We'll make our pricing clear and transparent so you know exactly what to expect before booking.",
      },
      {
        question: "Should I ever pay to apply for a scholarship?",
        answer: [
          "Most legitimate scholarships do not charge an application fee. However, some universities or scholarship programs may require an application or processing fee, especially when the scholarship is tied to an admission application. Always read the official application information carefully.",
          "If you're unsure whether a scholarship is legitimate, myScholy helps by listing verified opportunities from trusted organizations, making it easier to avoid scams and misleading offers.",
        ],
      },
    ],
  },
];

/** A short mixed set for marketing pages that only tease the FAQ. */
export const FEATURED_FAQS = [
  FAQ_GROUPS[0].faqs[0], // we do not award scholarships
  FAQ_GROUPS[1].faqs[0], // we do not write essays
  FAQ_GROUPS[2].faqs[0], // is myScholy free
  FAQ_GROUPS[2].faqs[2], // should I ever pay to apply
];
